---
title: "HW #2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Full Name 

  Answer: Sam Schwierking
  
## GitHub username

  Answer: Schwierk

## What did the instructor do in the first two commits? What are the commits IDs?

There are actually three commits now:

Create README:
5b20e6e3c657e5a6e6ab1c99d28e84b9efc78366

Update README:
7958af1beeaf537c8136cda7b4d1f2bc5e806550

Rename README to README.md:
5dd17cef356f30b711ed27eb24a99071d2a751f2

## Knit the instructor's hw1.Rmd. Are you able to do so without error? If you cannot, what errors did you counter?

I was able to do it without error.

## Also include an error/difficulty you encountered, or a tip for making Git/GitHub easier.

  Answer: For some reason when I am trying to use the function cd I have to type out the absolute path every time. I am not sure if that is an issue or not, but it still works. I just don't know in the future if that is going to hurt me, or if it just going to take longer time. I also learned that making commits are important for going back and looking at where you the last stage the code was in.
